### ISSUE TITLE
Why No Extra Marketing?

### ISSUE THREAD

**Issue by kivo360** [alison-carrera/onn#1]
This setup seems freaking amazing. Why aren't you marketing it more? It would be very good as an online learning system.

**Comment by alison-carrera** [comment]
Hi @kivo360, thanks for your feedback! How could I marketing it more? I'd be glad to hear you, thanks!

**Comment by kivo360** [comment]
Try pushing something on Reddit and HackerNews. If you can explain how various communities would benefit, people will jump at the opportunity to use your library.

**Comment by renanoliveira** [comment]
+1

Alison, I recommend writing a post in the medium about your opensource projects and posting on the channels that @kivo360  said. They are incredible, here at iFood we are already studying to use.
