### ISSUE TITLE
hard coded feature size

### ISSUE THREAD

**Issue by rajibhossen** [alison-carrera/onn#10]
I wanted to use the algorithm. However, my feature size is 51 and your algorithm can't validate this. it throws an error if features shape is not 2. 

```
if len(data.shape) != 2:
    raise Exception("Wrong dimension for this X data. It should have only two dimensions.")
```

**Comment by sh0wbit01** [comment]
remove this statement of code

**Comment by sh0wbit01** [comment]
> remove this statement of code



> I wanted to use the algorithm. However, my feature size is 51 and your algorithm can't validate this. it throws an error if features shape is not 2.
> 
> ```
> if len(data.shape) != 2:
>     raise Exception("Wrong dimension for this X data. It should have only two dimensions.")
> ```

remove this from code

**Comment by alison-carrera** [comment]
This part of the code is right. It looks as if your array has 3 dimensions or more in the shape array. The algorithm only accepts two dimensions arrays shape.

Example:

batch = 1
algorithm_features = 10

Numpy Array Shape: (1, 10) - This is OK

batch= 10
algorithm_features = 51

Numpy Array Shape: (10, 51) - This is OK

But arrays with shapes (1, 10, 51), (1, 2, 10, 51) don't work. I think you have extra dimensions in your array.

There are features shape for the model input (in your case 51) and shapes of the array which will be inputted into the dataset loader, it's different. I think the error message could be more friendly.
