### ISSUE TITLE
saving model or resuming training from a model

### ISSUE THREAD

**Issue by q138ben** [alison-carrera/onn#6]
Hi, the library looks amazing. I wonder if it is possible to save the model after training and to resume training from a saved model. Thanks.

**Comment by alison-carrera** [comment]
I think you can use the `model_instance.state_dict()` and save it as PyTorch documentation says [https://pytorch.org/tutorials/beginner/saving_loading_models.html](url)

I can't test it right now, but this model might need some special treatment for saving correctly, but theoretically, state_dict will work. Could you test for me? Thanks!

**Comment by q138ben** [comment]
Hi,


The model can be safely saved with the state_dict()? method. You don't have to change anything from the code.


Best regards,
Ben
________________________________
